[project]
name = "simplex-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "pybullet>=3.2.7",
    "pygame>=2.6.1",
    "pyopengl>=3.1.9",
    "toml>=0.10.2",
]
